export const SET_USER_AUTH_STATUS = "SET_USER_AUTH_STATUS";
export const SET_USER_AUTH_TOKEN = "SET_USER_AUTH_TOKEN";
export const SET_USER_TOKEN_EXPIRY_TIME = "SET_USER_TOKEN_EXPIRY_TIME";

export const FETCH_ALL_USERS = "FETCH_ALL_USERS";
export const FETCH_ALL_USERS_SUCCESS = "FETCH_ALL_USERS_SUCCESS";
export const FETCH_ALL_USERS_FAILURE = "FETCH_ALL_USERS_FAILURE";

export const FETCH_SELECTED_USER_DETAILS = " FETCH_SELECTED_USER_DETAILS";

export const FETCH_USER_POSTS = "FETCH_USER_POSTS";
export const FETCH_USER_POSTS_SUCCESS = "FETCH_USER_POSTS_SUCCESS";
export const FETCH_USER_POSTS_FAILURE = "FETCH_USER_POSTS_FAILURE";

export const FETCH_USER_TODOS = "FETCH_USER_TODOS";
export const FETCH_USER_TODOS_SUCCESS = "FETCH_USER_TODOS_SUCCESS";
export const FETCH_USER_TODOS_FAILURE = "FETCH_USER_TODOS_FAILURE";
